package gui;

import client.Client;
import java.awt.Color;
import java.rmi.RemoteException;
import javax.swing.JTextField;

/**
 *
 * @author Ernest Bieś, PWSZ Tarnów 2020
 */
public class GUI extends javax.swing.JFrame {

    private Client client;
    
    public GUI() {
        initComponents();
        client = new Client(this);
        client.connectServer();
    }
    
    private void checkNIP(String nip) {
        try {
            boolean isValid;
            isValid = client.getStub().validate(nip);
            jTextFieldStatus.setDisabledTextColor(Color.black);
            if(isValid) {
                jTextFieldStatus.setText("Wprowadzony NIP jest prawidłowy.");
            } else {
                jTextFieldStatus.setDisabledTextColor(Color.red);
                jTextFieldStatus.setText("Wprowadzony NIP jest nieprawidłowy.");
            }
        } catch (RemoteException ex) {
            jTextFieldStatus.setDisabledTextColor(Color.red);
            jTextFieldStatus.setText("Błąd połączenia.");
        }
    }
    
    public JTextField getTextFieldStatus() {
        return jTextFieldStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAbout = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();
        jLabelInfo = new javax.swing.JLabel();
        jLabelInfo1 = new javax.swing.JLabel();
        jTextFieldInput = new javax.swing.JTextField();
        jTextFieldStatus = new javax.swing.JTextField();
        jButtonValidate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NIPValidator");
        setResizable(false);

        jLabelAbout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAbout.setText("Walidator NIP");

        jLabelAuthor.setText("Ernest Bieś, PWSZ Tarnów 2020");

        jLabelInfo.setText("Wprowadź numer identyfikacji podatkowej");

        jLabelInfo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInfo1.setForeground(new java.awt.Color(51, 0, 204));
        jLabelInfo1.setText("(NIP):");

        jTextFieldStatus.setEditable(false);
        jTextFieldStatus.setEnabled(false);

        jButtonValidate.setText("Walidacja");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelAbout)
                        .addComponent(jLabelAuthor)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelInfo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelInfo1)))
                    .addComponent(jTextFieldStatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAuthor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfo)
                    .addComponent(jLabelInfo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonValidate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
        if(!jTextFieldInput.getText().isEmpty()) 
            checkNIP(jTextFieldInput.getText());
        else {
            jTextFieldStatus.setDisabledTextColor(Color.red);
            jTextFieldStatus.setText("Wprowadź numer NIP.");
        }
    }//GEN-LAST:event_jButtonValidateActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelInfo1;
    private javax.swing.JTextField jTextFieldInput;
    private javax.swing.JTextField jTextFieldStatus;
    // End of variables declaration//GEN-END:variables
}
